<?php

declare(strict_types=1);

namespace App\Shared\DataFixtures;

use App\Account\Factory\AccountFactory;
use App\Client\Factory\ClientFactory;
use App\Currency\Enum\Currency;
use App\Currency\Factory\CurrencyFactory;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AppFixtures extends Fixture
{
    private const array CURRENCIES = [
        Currency::AED->value => ['United Arab Emirates Dirham', 2],
        Currency::AFN->value => ['Afghan Afghani', 2],
        Currency::ALL->value => ['Albanian Lek', 2],
        Currency::AMD->value => ['Armenian Dram', 2],
        Currency::ANG->value => ['Netherlands Antillean Guilder', 2],
        Currency::AOA->value => ['Angolan Kwanza', 2],
        Currency::ARS->value => ['Argentine Peso', 2],
        Currency::AUD->value => ['Australian Dollar', 2],
        Currency::AWG->value => ['Aruban Florin', 2],
        Currency::AZN->value => ['Azerbaijani Manat', 2],
        Currency::BAM->value => ['Bosnia-Herzegovina Convertible Mark', 2],
        Currency::BBD->value => ['Barbadian Dollar', 2],
        Currency::BDT->value => ['Bangladeshi Taka', 2],
        Currency::BGN->value => ['Bulgarian Lev', 2],
        Currency::BHD->value => ['Bahraini Dinar', 3],
        Currency::BIF->value => ['Burundian Franc', 2],
        Currency::BMD->value => ['Bermudan Dollar', 2],
        Currency::BND->value => ['Brunei Dollar', 2],
        Currency::BOB->value => ['Bolivian Boliviano', 2],
        Currency::BRL->value => ['Brazilian Real', 2],
        Currency::BSD->value => ['Bahamian Dollar', 2],
        Currency::BTC->value => ['Bitcoin', 2],
        Currency::BTN->value => ['Bhutanese Ngultrum', 2],
        Currency::BWP->value => ['Botswanan Pula', 2],
        Currency::BYN->value => ['Belarusian Ruble', 2],
        Currency::BYR->value => ['Belarusian Ruble', 2],
        Currency::BZD->value => ['Belize Dollar', 2],
        Currency::CAD->value => ['Canadian Dollar', 2],
        Currency::CDF->value => ['Congolese Franc', 2],
        Currency::CHF->value => ['Swiss Franc', 2],
        Currency::CLF->value => ['Chilean Unit of Account (UF)', 2],
        Currency::CLP->value => ['Chilean Peso', 2],
        Currency::CNY->value => ['Chinese Yuan', 2],
        Currency::COP->value => ['Colombian Peso', 2],
        Currency::CRC->value => ['Costa Rican Colon', 2],
        Currency::CUC->value => ['Cuban Convertible Peso', 2],
        Currency::CUP->value => ['Cuban Peso', 2],
        Currency::CVE->value => ['Cape Verdean Escudo', 0],
        Currency::CZK->value => ['Czech Republic Koruna', 2],
        Currency::DJF->value => ['Djiboutian Franc', 0],
        Currency::DKK->value => ['Danish Krone', 2],
        Currency::DOP->value => ['Dominican Peso', 2],
        Currency::DZD->value => ['Algerian Dinar', 2],
        Currency::EEK->value => ['Estonian Kroon', 2],
        Currency::EGP->value => ['Egyptian Pound', 2],
        Currency::ERN->value => ['Eritrean Nakfa', 2],
        Currency::ETB->value => ['Ethiopian Birr', 2],
        Currency::EUR->value => ['Euro', 2],
        Currency::FJD->value => ['Fijian Dollar', 2],
        Currency::FKP->value => ['Falkland Islands Pound', 2],
        Currency::GBP->value => ['British Pound Sterling', 2],
        Currency::GEL->value => ['Georgian Lari', 2],
        Currency::GGP->value => ['Guernsey Pound', 2],
        Currency::GHS->value => ['Ghanaian Cedi', 2],
        Currency::GIP->value => ['Gibraltar Pound', 2],
        Currency::GMD->value => ['Gambian Dalasi', 2],
        Currency::GNF->value => ['Guinean Franc', 2],
        Currency::GTQ->value => ['Guatemalan Quetzal', 2],
        Currency::GYD->value => ['Guyanaese Dollar', 2],
        Currency::HKD->value => ['Hong Kong Dollar', 2],
        Currency::HNL->value => ['Honduran Lempira', 2],
        Currency::HRK->value => ['Croatian Kuna', 2],
        Currency::HTG->value => ['Haitian Gourde', 2],
        Currency::HUF->value => ['Hungarian Forint', 2],
        Currency::IDR->value => ['Indonesian Rupiah', 0],
        Currency::ILS->value => ['Israeli New Sheqel', 2],
        Currency::IMP->value => ['Manx pound', 2],
        Currency::INR->value => ['Indian Rupee', 2],
        Currency::IQD->value => ['Iraqi Dinar', 3],
        Currency::IRR->value => ['Iranian Rial', 2],
        Currency::ISK->value => ['Icelandic Krona', 2],
        Currency::JEP->value => ['Jersey Pound', 2],
        Currency::JMD->value => ['Jamaican Dollar', 2],
        Currency::JOD->value => ['Jordanian Dinar', 3],
        Currency::JPY->value => ['Japanese Yen', 0],
        Currency::KES->value => ['Kenyan Shilling', 2],
        Currency::KGS->value => ['Kyrgystani Som', 2],
        Currency::KHR->value => ['Cambodian Riel', 2],
        Currency::KMF->value => ['Comorian Franc', 0],
        Currency::KPW->value => ['North Korean Won', 2],
        Currency::KRW->value => ['South Korean Won', 0],
        Currency::KWD->value => ['Kuwaiti Dinar', 3],
        Currency::KYD->value => ['Cayman Islands Dollar', 2],
        Currency::KZT->value => ['Kazakhstani Tenge', 2],
        Currency::LAK->value => ['Laotian Kip', 2],
        Currency::LBP->value => ['Lebanese Pound', 2],
        Currency::LKR->value => ['Sri Lankan Rupee', 2],
        Currency::LRD->value => ['Liberian Dollar', 2],
        Currency::LSL->value => ['Lesotho Loti', 2],
        Currency::LTL->value => ['Lithuanian Litas', 2],
        Currency::LVL->value => ['Latvian Lats', 2],
        Currency::LYD->value => ['Libyan Dinar', 3],
        Currency::MAD->value => ['Moroccan Dirham', 2],
        Currency::MDL->value => ['Moldovan Leu', 2],
        Currency::MGA->value => ['Malagasy Ariary', 2],
        Currency::MKD->value => ['Macedonian Denar', 2],
        Currency::MMK->value => ['Myanma Kyat', 2],
        Currency::MNT->value => ['Mongolian Tugrik', 2],
        Currency::MOP->value => ['Macanese Pataca', 2],
        Currency::MRO->value => ['Mauritanian Ouguiya', 2],
        Currency::MUR->value => ['Mauritian Rupee', 2],
        Currency::MVR->value => ['Maldivian Rufiyaa', 2],
        Currency::MWK->value => ['Malawian Kwacha', 2],
        Currency::MXN->value => ['Mexican Peso', 2],
        Currency::MYR->value => ['Malaysian Ringgit', 2],
        Currency::MZN->value => ['Mozambican Metical', 2],
        Currency::NAD->value => ['Namibian Dollar', 2],
        Currency::NGN->value => ['Nigerian Naira', 2],
        Currency::NIO->value => ['Nicaraguan Cordoba', 2],
        Currency::NOK->value => ['Norwegian Krone', 2],
        Currency::NPR->value => ['Nepalese Rupee', 2],
        Currency::NZD->value => ['New Zealand Dollar', 2],
        Currency::OMR->value => ['Omani Rial', 3],
        Currency::PAB->value => ['Panamanian Balboa', 2],
        Currency::PEN->value => ['Peruvian Nuevo Sol', 2],
        Currency::PGK->value => ['Papua New Guinean Kina', 2],
        Currency::PHP->value => ['Philippine Peso', 2],
        Currency::PKR->value => ['Pakistani Rupee', 2],
        Currency::PLN->value => ['Polish Zloty', 2],
        Currency::PYG->value => ['Paraguayan Guarani', 0],
        Currency::QAR->value => ['Qatari Rial', 2],
        Currency::RON->value => ['Romanian Leu', 2],
        Currency::RSD->value => ['Serbian Dinar', 2],
        Currency::RUB->value => ['Russian Ruble', 2],
        Currency::RWF->value => ['Rwandan Franc', 0],
        Currency::SAR->value => ['Saudi Riyal', 2],
        Currency::SBD->value => ['Solomon Islands Dollar', 2],
        Currency::SCR->value => ['Seychellois Rupee', 2],
        Currency::SDG->value => ['Sudanese Pound', 2],
        Currency::SEK->value => ['Swedish Krona', 2],
        Currency::SGD->value => ['Singapore Dollar', 2],
        Currency::SHP->value => ['Saint Helena Pound', 2],
        Currency::SLL->value => ['Sierra Leonean Leone', 2],
        Currency::SOS->value => ['Somali Shilling', 2],
        Currency::SRD->value => ['Surinamese Dollar', 2],
        Currency::STD->value => ['Sao Tome and Principe Dobra', 2],
        Currency::SVC->value => ['Salvadoran Colon', 2],
        Currency::SYP->value => ['Syrian Pound', 2],
        Currency::SZL->value => ['Swazi Lilangeni', 2],
        Currency::THB->value => ['Thai Baht', 2],
        Currency::TJS->value => ['Tajikistani Somoni', 2],
        Currency::TMT->value => ['Turkmenistani Manat', 2],
        Currency::TND->value => ['Tunisian Dinar', 3],
        Currency::TOP->value => ["Tonga Pa'anga", 2],
        Currency::TRY->value => ['Turkish Lira', 2],
        Currency::TTD->value => ['Trinidad and Tobago Dollar', 2],
        Currency::TWD->value => ['New Taiwan Dollar', 2],
        Currency::TZS->value => ['Tanzanian Shilling', 2],
        Currency::UAH->value => ['Ukrainian Hryvnia', 2],
        Currency::UGX->value => ['Ugandan Shilling', 0],
        Currency::USD->value => ['United States Dollar', 2],
        Currency::UYU->value => ['Uruguayan Peso', 2],
        Currency::UZS->value => ['Uzbekistan Som', 2],
        Currency::VEF->value => ['Venezuelan Bolivar Fuerte', 2],
        Currency::VND->value => ['Vietnamese Dong', 0],
        Currency::VUV->value => ['Vanuatu Vatu', 0],
        Currency::WST->value => ['Samoan Tala', 2],
        Currency::XAF->value => ['CFA Franc BEAC', 0],
        Currency::XAG->value => ['Silver (troy ounce)', 2],
        Currency::XAU->value => ['Gold (troy ounce)', 2],
        Currency::XCD->value => ['East Caribbean Dollar', 2],
        Currency::XDR->value => ['Special Drawing Rights', 2],
        Currency::XOF->value => ['CFA Franc BCEAO', 0],
        Currency::XPF->value => ['CFP Franc', 0],
        Currency::YER->value => ['Yemeni Rial', 2],
        Currency::ZAR->value => ['South African Rand', 2],
        Currency::ZMK->value => ['Zambian Kwacha (pre-2013)', 2],
        Currency::ZMW->value => ['Zambian Kwacha', 2],
        Currency::ZWL->value => ['Zimbabwean Dollar', 2],
    ];

    private const array ACCOUNT_CURRENCIES = [
        Currency::USD->value => 10_000,
        Currency::EUR->value => 10_000,
        Currency::GBP->value => 10_000,
        Currency::JPY->value => 1_500_000,
        Currency::ISK->value => 1_300_000,
    ];

    public function load(ObjectManager $manager): void
    {
        $currencies = [];

        foreach (self::CURRENCIES as $code => $data) {
            $currencies[$code] = CurrencyFactory::createOne([
                'code' => $code,
                'name' => $data[0],
                'decimalPlaces' => $data[1],
            ]);
        }

        $clients = ClientFactory::createMany(2);

        foreach ($clients as $client) {
            foreach (self::ACCOUNT_CURRENCIES as $currency => $startingBalance) {
                $account = AccountFactory::createOne([
                    'client' => $client,
                    'currency' => $currencies[$currency],
                    'balance' => $startingBalance,
                ]);

                $client->addAccount($account);
            }
        }
    }
}
