<?php

declare(strict_types=1);

namespace App\Shared\DataFixtures;

use App\Account\Factory\AccountFactory;
use App\Client\Factory\ClientFactory;
use App\Currency\Enum\CurrencyCode;
use App\Currency\Factory\CurrencyFactory;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AppFixtures extends Fixture
{
    private const array CURRENCIES = [
        CurrencyCode::AED->value => ['United Arab Emirates Dirham', 2],
        CurrencyCode::AFN->value => ['Afghan Afghani', 2],
        CurrencyCode::ALL->value => ['Albanian Lek', 2],
        CurrencyCode::AMD->value => ['Armenian Dram', 2],
        CurrencyCode::ANG->value => ['Netherlands Antillean Guilder', 2],
        CurrencyCode::AOA->value => ['Angolan Kwanza', 2],
        CurrencyCode::ARS->value => ['Argentine Peso', 2],
        CurrencyCode::AUD->value => ['Australian Dollar', 2],
        CurrencyCode::AWG->value => ['Aruban Florin', 2],
        CurrencyCode::AZN->value => ['Azerbaijani Manat', 2],
        CurrencyCode::BAM->value => ['Bosnia-Herzegovina Convertible Mark', 2],
        CurrencyCode::BBD->value => ['Barbadian Dollar', 2],
        CurrencyCode::BDT->value => ['Bangladeshi Taka', 2],
        CurrencyCode::BGN->value => ['Bulgarian Lev', 2],
        CurrencyCode::BHD->value => ['Bahraini Dinar', 3],
        CurrencyCode::BIF->value => ['Burundian Franc', 2],
        CurrencyCode::BMD->value => ['Bermudan Dollar', 2],
        CurrencyCode::BND->value => ['Brunei Dollar', 2],
        CurrencyCode::BOB->value => ['Bolivian Boliviano', 2],
        CurrencyCode::BRL->value => ['Brazilian Real', 2],
        CurrencyCode::BSD->value => ['Bahamian Dollar', 2],
        CurrencyCode::BTC->value => ['Bitcoin', 2],
        CurrencyCode::BTN->value => ['Bhutanese Ngultrum', 2],
        CurrencyCode::BWP->value => ['Botswanan Pula', 2],
        CurrencyCode::BYN->value => ['Belarusian Ruble', 2],
        CurrencyCode::BYR->value => ['Belarusian Ruble', 2],
        CurrencyCode::BZD->value => ['Belize Dollar', 2],
        CurrencyCode::CAD->value => ['Canadian Dollar', 2],
        CurrencyCode::CDF->value => ['Congolese Franc', 2],
        CurrencyCode::CHF->value => ['Swiss Franc', 2],
        CurrencyCode::CLF->value => ['Chilean Unit of Account (UF)', 2],
        CurrencyCode::CLP->value => ['Chilean Peso', 2],
        CurrencyCode::CNY->value => ['Chinese Yuan', 2],
        CurrencyCode::COP->value => ['Colombian Peso', 2],
        CurrencyCode::CRC->value => ['Costa Rican Colon', 2],
        CurrencyCode::CUC->value => ['Cuban Convertible Peso', 2],
        CurrencyCode::CUP->value => ['Cuban Peso', 2],
        CurrencyCode::CVE->value => ['Cape Verdean Escudo', 0],
        CurrencyCode::CZK->value => ['Czech Republic Koruna', 2],
        CurrencyCode::DJF->value => ['Djiboutian Franc', 0],
        CurrencyCode::DKK->value => ['Danish Krone', 2],
        CurrencyCode::DOP->value => ['Dominican Peso', 2],
        CurrencyCode::DZD->value => ['Algerian Dinar', 2],
        CurrencyCode::EEK->value => ['Estonian Kroon', 2],
        CurrencyCode::EGP->value => ['Egyptian Pound', 2],
        CurrencyCode::ERN->value => ['Eritrean Nakfa', 2],
        CurrencyCode::ETB->value => ['Ethiopian Birr', 2],
        CurrencyCode::EUR->value => ['Euro', 2],
        CurrencyCode::FJD->value => ['Fijian Dollar', 2],
        CurrencyCode::FKP->value => ['Falkland Islands Pound', 2],
        CurrencyCode::GBP->value => ['British Pound Sterling', 2],
        CurrencyCode::GEL->value => ['Georgian Lari', 2],
        CurrencyCode::GGP->value => ['Guernsey Pound', 2],
        CurrencyCode::GHS->value => ['Ghanaian Cedi', 2],
        CurrencyCode::GIP->value => ['Gibraltar Pound', 2],
        CurrencyCode::GMD->value => ['Gambian Dalasi', 2],
        CurrencyCode::GNF->value => ['Guinean Franc', 2],
        CurrencyCode::GTQ->value => ['Guatemalan Quetzal', 2],
        CurrencyCode::GYD->value => ['Guyanaese Dollar', 2],
        CurrencyCode::HKD->value => ['Hong Kong Dollar', 2],
        CurrencyCode::HNL->value => ['Honduran Lempira', 2],
        CurrencyCode::HRK->value => ['Croatian Kuna', 2],
        CurrencyCode::HTG->value => ['Haitian Gourde', 2],
        CurrencyCode::HUF->value => ['Hungarian Forint', 2],
        CurrencyCode::IDR->value => ['Indonesian Rupiah', 0],
        CurrencyCode::ILS->value => ['Israeli New Sheqel', 2],
        CurrencyCode::IMP->value => ['Manx pound', 2],
        CurrencyCode::INR->value => ['Indian Rupee', 2],
        CurrencyCode::IQD->value => ['Iraqi Dinar', 3],
        CurrencyCode::IRR->value => ['Iranian Rial', 2],
        CurrencyCode::ISK->value => ['Icelandic Krona', 2],
        CurrencyCode::JEP->value => ['Jersey Pound', 2],
        CurrencyCode::JMD->value => ['Jamaican Dollar', 2],
        CurrencyCode::JOD->value => ['Jordanian Dinar', 3],
        CurrencyCode::JPY->value => ['Japanese Yen', 0],
        CurrencyCode::KES->value => ['Kenyan Shilling', 2],
        CurrencyCode::KGS->value => ['Kyrgystani Som', 2],
        CurrencyCode::KHR->value => ['Cambodian Riel', 2],
        CurrencyCode::KMF->value => ['Comorian Franc', 0],
        CurrencyCode::KPW->value => ['North Korean Won', 2],
        CurrencyCode::KRW->value => ['South Korean Won', 0],
        CurrencyCode::KWD->value => ['Kuwaiti Dinar', 3],
        CurrencyCode::KYD->value => ['Cayman Islands Dollar', 2],
        CurrencyCode::KZT->value => ['Kazakhstani Tenge', 2],
        CurrencyCode::LAK->value => ['Laotian Kip', 2],
        CurrencyCode::LBP->value => ['Lebanese Pound', 2],
        CurrencyCode::LKR->value => ['Sri Lankan Rupee', 2],
        CurrencyCode::LRD->value => ['Liberian Dollar', 2],
        CurrencyCode::LSL->value => ['Lesotho Loti', 2],
        CurrencyCode::LTL->value => ['Lithuanian Litas', 2],
        CurrencyCode::LVL->value => ['Latvian Lats', 2],
        CurrencyCode::LYD->value => ['Libyan Dinar', 3],
        CurrencyCode::MAD->value => ['Moroccan Dirham', 2],
        CurrencyCode::MDL->value => ['Moldovan Leu', 2],
        CurrencyCode::MGA->value => ['Malagasy Ariary', 2],
        CurrencyCode::MKD->value => ['Macedonian Denar', 2],
        CurrencyCode::MMK->value => ['Myanma Kyat', 2],
        CurrencyCode::MNT->value => ['Mongolian Tugrik', 2],
        CurrencyCode::MOP->value => ['Macanese Pataca', 2],
        CurrencyCode::MRO->value => ['Mauritanian Ouguiya', 2],
        CurrencyCode::MUR->value => ['Mauritian Rupee', 2],
        CurrencyCode::MVR->value => ['Maldivian Rufiyaa', 2],
        CurrencyCode::MWK->value => ['Malawian Kwacha', 2],
        CurrencyCode::MXN->value => ['Mexican Peso', 2],
        CurrencyCode::MYR->value => ['Malaysian Ringgit', 2],
        CurrencyCode::MZN->value => ['Mozambican Metical', 2],
        CurrencyCode::NAD->value => ['Namibian Dollar', 2],
        CurrencyCode::NGN->value => ['Nigerian Naira', 2],
        CurrencyCode::NIO->value => ['Nicaraguan Cordoba', 2],
        CurrencyCode::NOK->value => ['Norwegian Krone', 2],
        CurrencyCode::NPR->value => ['Nepalese Rupee', 2],
        CurrencyCode::NZD->value => ['New Zealand Dollar', 2],
        CurrencyCode::OMR->value => ['Omani Rial', 3],
        CurrencyCode::PAB->value => ['Panamanian Balboa', 2],
        CurrencyCode::PEN->value => ['Peruvian Nuevo Sol', 2],
        CurrencyCode::PGK->value => ['Papua New Guinean Kina', 2],
        CurrencyCode::PHP->value => ['Philippine Peso', 2],
        CurrencyCode::PKR->value => ['Pakistani Rupee', 2],
        CurrencyCode::PLN->value => ['Polish Zloty', 2],
        CurrencyCode::PYG->value => ['Paraguayan Guarani', 0],
        CurrencyCode::QAR->value => ['Qatari Rial', 2],
        CurrencyCode::RON->value => ['Romanian Leu', 2],
        CurrencyCode::RSD->value => ['Serbian Dinar', 2],
        CurrencyCode::RUB->value => ['Russian Ruble', 2],
        CurrencyCode::RWF->value => ['Rwandan Franc', 0],
        CurrencyCode::SAR->value => ['Saudi Riyal', 2],
        CurrencyCode::SBD->value => ['Solomon Islands Dollar', 2],
        CurrencyCode::SCR->value => ['Seychellois Rupee', 2],
        CurrencyCode::SDG->value => ['Sudanese Pound', 2],
        CurrencyCode::SEK->value => ['Swedish Krona', 2],
        CurrencyCode::SGD->value => ['Singapore Dollar', 2],
        CurrencyCode::SHP->value => ['Saint Helena Pound', 2],
        CurrencyCode::SLL->value => ['Sierra Leonean Leone', 2],
        CurrencyCode::SOS->value => ['Somali Shilling', 2],
        CurrencyCode::SRD->value => ['Surinamese Dollar', 2],
        CurrencyCode::STD->value => ['Sao Tome and Principe Dobra', 2],
        CurrencyCode::SVC->value => ['Salvadoran Colon', 2],
        CurrencyCode::SYP->value => ['Syrian Pound', 2],
        CurrencyCode::SZL->value => ['Swazi Lilangeni', 2],
        CurrencyCode::THB->value => ['Thai Baht', 2],
        CurrencyCode::TJS->value => ['Tajikistani Somoni', 2],
        CurrencyCode::TMT->value => ['Turkmenistani Manat', 2],
        CurrencyCode::TND->value => ['Tunisian Dinar', 3],
        CurrencyCode::TOP->value => ["Tonga Pa'anga", 2],
        CurrencyCode::TRY->value => ['Turkish Lira', 2],
        CurrencyCode::TTD->value => ['Trinidad and Tobago Dollar', 2],
        CurrencyCode::TWD->value => ['New Taiwan Dollar', 2],
        CurrencyCode::TZS->value => ['Tanzanian Shilling', 2],
        CurrencyCode::UAH->value => ['Ukrainian Hryvnia', 2],
        CurrencyCode::UGX->value => ['Ugandan Shilling', 0],
        CurrencyCode::USD->value => ['United States Dollar', 2],
        CurrencyCode::UYU->value => ['Uruguayan Peso', 2],
        CurrencyCode::UZS->value => ['Uzbekistan Som', 2],
        CurrencyCode::VEF->value => ['Venezuelan Bolivar Fuerte', 2],
        CurrencyCode::VND->value => ['Vietnamese Dong', 0],
        CurrencyCode::VUV->value => ['Vanuatu Vatu', 0],
        CurrencyCode::WST->value => ['Samoan Tala', 2],
        CurrencyCode::XAF->value => ['CFA Franc BEAC', 0],
        CurrencyCode::XAG->value => ['Silver (troy ounce)', 2],
        CurrencyCode::XAU->value => ['Gold (troy ounce)', 2],
        CurrencyCode::XCD->value => ['East Caribbean Dollar', 2],
        CurrencyCode::XDR->value => ['Special Drawing Rights', 2],
        CurrencyCode::XOF->value => ['CFA Franc BCEAO', 0],
        CurrencyCode::XPF->value => ['CFP Franc', 0],
        CurrencyCode::YER->value => ['Yemeni Rial', 2],
        CurrencyCode::ZAR->value => ['South African Rand', 2],
        CurrencyCode::ZMK->value => ['Zambian Kwacha (pre-2013)', 2],
        CurrencyCode::ZMW->value => ['Zambian Kwacha', 2],
        CurrencyCode::ZWL->value => ['Zimbabwean Dollar', 2],
    ];

    private const array ACCOUNT_CURRENCIES = [
        CurrencyCode::USD->value => 100_000,
        CurrencyCode::EUR->value => 100_000,
        CurrencyCode::GBP->value => 100_000,
        CurrencyCode::JPY->value => 1_500_000,
        CurrencyCode::ISK->value => 12_622_000,
    ];

    public function load(ObjectManager $manager): void
    {
        $currencies = [];

        foreach (self::CURRENCIES as $code => $data) {
            $currencies[$code] = CurrencyFactory::createOne([
                'code' => $code,
                'name' => $data[0],
                'decimalPlaces' => $data[1],
            ]);
        }

        $clients = ClientFactory::createMany(2);

        foreach ($clients as $client) {
            foreach (self::ACCOUNT_CURRENCIES as $currency => $startingBalance) {
                $account = AccountFactory::createOne([
                    'client' => $client,
                    'currency' => $currencies[$currency],
                    'balance' => $startingBalance,
                ]);

                $client->addAccount($account);
            }
        }
    }
}
