### Transfer funds between accounts
POST http://{{host}}/api/v1/transfer
Accept: application/json
Content-Type: application/json

{
    "senderId": "1f04486a-9648-6de8-b8ab-bf775cf412e4",
    "recipientId": "1f04486a-9644-691e-96a9-bf775cf412e4",
    "amount": 1000,
    "currency": "JPY"
}
###
