### Transfer funds between accounts
POST http://{{host}}/api/v1/transfer
Accept: application/json
Content-Type: application/json

{
    "senderAccountId": "1f045716-9eb9-6e2c-8d02-6bab9d363e86",
    "recipientAccountId": "1f045716-9eb5-6660-a5df-6bab9d363e86",
    "amount": 120.23,
    "currency": "USD"
}
###
