parameters:
    currency_rate.active_source: "FKE"

services:
    App\Currency\Interface\CurrencyRateImporterInterface: '@App\Currency\Service\FakeCurrencyRateImporter'
    App\Currency\Repository\CurrencyRateRepositoryInterface: '@App\Currency\Repository\Doctrine\CurrencyRateRepository'
    App\Currency\Repository\CurrencyRepositoryInterface: '@App\Currency\Repository\Doctrine\CurrencyRepository'
